### ISSUE TITLE
Failed to copy Doxygen output in CI

### ISSUE THREAD

**Issue by mmurooka** [isri-aist/NMPC#3]
https://github.com/isri-aist/NMPC/actions/runs/3627105794/jobs/6116692285
```
+ git checkout --quiet gh-pages
warning: unable to rmdir 'cmake': Directory not empty
+ rm -rf nmpc_ddp/ nmpc_fmpc/ nmpc_cgmres/
+ cp -r /home/runner/work/NMPC/NMPC/catkin_ws/build/nmpc_ddp/doc/html/ nmpc_ddp
cp: cannot stat '/home/runner/work/NMPC/NMPC/catkin_ws/build/nmpc_ddp/doc/html/': No such file or directory
```

After https://github.com/isri-aist/NMPC/pull/1, the output directories of Doxygen document have changed from `catkin_ws/build/nmpc_ddp/doc/html/` to `catkin_ws/build/nmpc_ddp/doc/doxygen-html/`. It's OK, but do you know why?

**Comment by gergondet** [comment]
The above commit should fix this. This is because of the adoption of jrl-cmakemodules which work very much the same way but default to doxygen-html
